// Code generated by Kitex v0.4.4. DO NOT EDIT.

package relationservice

import (
	"Mini_DouYin/kitex_gen/relation"
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return relationServiceServiceInfo
}

var relationServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "RelationService"
	handlerType := (*relation.RelationService)(nil)
	methods := map[string]kitex.MethodInfo{
		"ActionRelation": kitex.NewMethodInfo(actionRelationHandler, newRelationServiceActionRelationArgs, newRelationServiceActionRelationResult, false),
		"ListAllOperate": kitex.NewMethodInfo(listAllOperateHandler, newRelationServiceListAllOperateArgs, newRelationServiceListAllOperateResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "relation",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func actionRelationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*relation.RelationServiceActionRelationArgs)
	realResult := result.(*relation.RelationServiceActionRelationResult)
	success, err := handler.(relation.RelationService).ActionRelation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceActionRelationArgs() interface{} {
	return relation.NewRelationServiceActionRelationArgs()
}

func newRelationServiceActionRelationResult() interface{} {
	return relation.NewRelationServiceActionRelationResult()
}

func listAllOperateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*relation.RelationServiceListAllOperateArgs)
	realResult := result.(*relation.RelationServiceListAllOperateResult)
	success, err := handler.(relation.RelationService).ListAllOperate(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceListAllOperateArgs() interface{} {
	return relation.NewRelationServiceListAllOperateArgs()
}

func newRelationServiceListAllOperateResult() interface{} {
	return relation.NewRelationServiceListAllOperateResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ActionRelation(ctx context.Context, req *relation.ActionRelationRequest) (r *relation.ActionRelationResponse, err error) {
	var _args relation.RelationServiceActionRelationArgs
	_args.Req = req
	var _result relation.RelationServiceActionRelationResult
	if err = p.c.Call(ctx, "ActionRelation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListAllOperate(ctx context.Context, req *relation.ListAllOperateRequest) (r *relation.ListAllOperateResponse, err error) {
	var _args relation.RelationServiceListAllOperateArgs
	_args.Req = req
	var _result relation.RelationServiceListAllOperateResult
	if err = p.c.Call(ctx, "ListAllOperate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
